# Generated by Django 4.2.16 on 2025-05-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_songs',
        ),
    ]
