# Generated by Django 4.2.16 on 2025-04-20 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
