# Generated by Django 4.2.16 on 2025-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_playlist_options_remove_playlist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
